#!groovy
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
        }
    options {
      buildDiscarder logRotator(artifactNumToKeepStr: '10', numToKeepStr: '10')
      timestamps()
    }
    environment {
      IMAGE_BASE = 'vyurchenko1986/pet-clinic'
      IMAGE_TAG = "v$BUILD_NUMBER"
      IMAGE_NAME = "${env.IMAGE_BASE}:${env.IMAGE_TAG}"
      IMAGE_NAME_LATEST = "${env.IMAGE_BASE}:latest"
      DOCKERFILE_NAME = "docker/Dockerfile"
      AWS_ACCESS_KEY_ID     = credentials('terraform-aws-secret-key-id')
      AWS_SECRET_ACCESS_KEY = credentials('terraform-aws-secret-access-key')
      DEV_IP = ''
      PROD_IP = ''
    }
    stages {

        stage("Building and testing app") {
          stages {
            stage("Get sources from GitHub") {
              steps {
                checkout scm
              }
            }
            
            stage("Testing stage") {
              steps {
                dir ('app_source_code/spring-petclinic-main') {
                   sh 'sh mvnw test'
                   sh 'sh mvnw surefire-report:report'
                   junit 'target/surefire-reports/TEST-*.xml'
                }
              }
            }
            
            stage("Build artifact") {
              steps {
                dir ('app_source_code/spring-petclinic-main') {
                   sh 'sh mvnw package -DskipTests'
                }
                dir ('.') {
                   echo "===========Copying artifact to docker folder============="
                   sh 'cp app_source_code/spring-petclinic-main/target/*.jar docker/output/app.jar'
                   echo "===========Archiving artifact for Jenkins============="
                   archiveArtifacts(artifacts: 'app_source_code/spring-petclinic-main/target/*.jar')
                   archiveArtifacts(artifacts: 'app_source_code/spring-petclinic-main/target/site/surefire-report.html')
                   echo "===========Artifact has copied to Docker folder and Archived for Jenkins============="
                }
              }
            }

          }
        }
        
        stage("Docker login") {
            steps {
                echo "===========docker login============="
                withCredentials([usernamePassword(credentialsId: 'docker-hub-secret-access-key', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
                    sh """
                    docker login -u $USERNAME -p $PASSWORD
                    """
                echo "===========docker login Success!============="
                }
            }
        }


        stage('Push images to registry') {
              steps {
                sh 'pwd'
                script {
                  sh 'pwd'
                  def dockerImage = docker.build("${IMAGE_NAME}", "-f ${DOCKERFILE_NAME} .")
                  docker.withRegistry('', 'docker-hub-secret-access-key') {
                    dockerImage.push()
                    dockerImage.push("latest")
                  }
                  echo "Pushed Docker Image: ${IMAGE_NAME}"
                }

                sh "docker rmi ${IMAGE_NAME} ${IMAGE_NAME_LATEST}"
                sh "docker image prune -a -f"
                sh "docker system prune -a -f"
              }
        }
        
        stage('Build Environment with Terraform') {
          /*input{
             message "Do you want to Build Dev Environment with Terraform?"
          }*/
          steps {
            checkout scm
            dir ('terraform') {
                sh """
                terraform init
                terraform apply --auto-approve
                """
                script {
                  DEV_IP = sh(returnStdout: true, script: "terraform output -raw dev_server_ip").trim()
                  PROD_IP = sh(returnStdout: true, script: "terraform output -raw prod_server_ip").trim()
                }
                writeFile (file: '../ansible/hosts.txt', text: '[dev]\n' + DEV_IP + '\n' + '[prod]\n' + PROD_IP + '\n')

            }
          }
        }
        stage('Configuring Dev Environment with Ansible') {
          /*input{
             message "Do you want to Configuring Dev Environment?"
          }*/
          steps {
            dir ('ansible') {
              sh 'echo now you are in the'
              sh 'pwd'
              ansiblePlaybook(credentialsId: 'ansible-deployer-key', inventory: 'hosts.txt', playbook: 'devenv.yml')
            }
          }
          post {
            always {
              withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'TOKEN'), string(credentialsId: 'telegram-bot-chatid', variable: 'CHAT_ID')]) {
              sh  ("""
              curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='*Job name - * *${env.JOB_NAME}*, *Build number - * *${BUILD_NUMBER}*, *[Dev] Testing server address - * *http://${DEV_IP}:8080*' 
              """)
              }
            }
          }
        }


        stage('Configuring Prod Environment with Ansible') {
          input{
             message "Push app to Production?"
          }
          steps {
            dir ('ansible') {
              sh 'echo now you are in the'
              sh 'pwd'
              ansiblePlaybook(credentialsId: 'ansible-deployer-key', inventory: 'hosts.txt', playbook: 'prodenv.yml')
            }
          }
          post {
            always {
              withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'TOKEN'), string(credentialsId: 'telegram-bot-chatid', variable: 'CHAT_ID')]) {
              sh  ("""
              curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='*Job name - * *${env.JOB_NAME}*, *Build number - * *${BUILD_NUMBER}*, *[Prod] Testing server address - * *http://${PROD_IP}:8080*' 
              """)
              }
            }
          }
        }
        stage('Destroy Environment') {
          input{
             message "Do you want to Destroy Dev Environment?"
          }
          steps {
            dir ('terraform') {
                sh 'terraform destroy --auto-approve'
              
            }
          }
        }
    }
    post {
     success { 
        withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'TOKEN'), string(credentialsId: 'telegram-bot-chatid', variable: 'CHAT_ID')]) {
        sh  ("""
            curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='*${env.JOB_NAME}* : POC *Branch*: ${env.GIT_BRANCH} *Build* : OK *Published* = YES'
        """)
        }
     }

     aborted {
        withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'TOKEN'), string(credentialsId: 'telegram-bot-chatid', variable: 'CHAT_ID')]) {
        sh  ("""
            curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='*${env.JOB_NAME}* : POC *Branch*: ${env.GIT_BRANCH} *Build* : `Aborted` *Published* = `Aborted`'
        """)
        }
     
     }
     failure {
        withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'TOKEN'), string(credentialsId: 'telegram-bot-chatid', variable: 'CHAT_ID')]) {
        sh  ("""
            curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='*${env.JOB_NAME}* : POC  *Branch*: ${env.GIT_BRANCH} *Build* : `not OK` *Published* = `no`'
        """)
        }
     }

    }
}
